# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 182)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxAccount = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxAccount.setGeometry(QtCore.QRect(20, 30, 241, 22))
        self.comboBoxAccount.setFrame(True)
        self.comboBoxAccount.setObjectName("comboBoxAccount")
        self.btnVaoGame = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnVaoGame.setGeometry(QtCore.QRect(280, 30, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnVaoGame.setFont(font)
        self.btnVaoGame.setObjectName("btnVaoGame")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 241, 101))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 4, 131, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 4, 111, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mượn tài khoản - NetBeHai"))
        self.btnVaoGame.setText(_translate("MainWindow", "Vào Game"))
        self.label.setText(_translate("MainWindow", "Nếu bạn có tài khoản muốn từ thiện thì liên hệ cho chủ tiệm để được thêm vào (Đồng thời được cày miễn phí đó nha :D)"))
        self.label_2.setText(_translate("MainWindow", "Chọn tài khoản:"))
        self.pushButton.setText(_translate("MainWindow", "Làm Mới"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
